# This workflow will do a clean install of node dependencies, build the source code and run tests on the selected version of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test, and Deploy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --if-present
      - run: npm run build --if-present
        env:
          CI: true
      - run: npm test
        env:
          CI: true
      - run: print(${{ github }})
      - run: echo ${{ github.ref }}
        if: contains(github.ref, 'release')

  deploy-aws:
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci --if-present
      - run: npm run build --if-present
        env:
          CI: true
      - run: npm test
        env:
          CI: true
      - run: npm run migrate
        env:
          CI: true
          WORLDS_ACCESS_KEY_ID: ${{secrets.WORLDS_ACCESS_KEY_ID}}
          WORLDS_SECRET_ACCESS_KEY: ${{secrets.WORLDS_SECRET_ACCESS_KEY}}
      - run: npm run deploy
        env:
          CI: true
          WORLDS_ACCESS_KEY_ID: ${{secrets.WORLDS_ACCESS_KEY_ID}}
          WORLDS_SECRET_ACCESS_KEY: ${{secrets.WORLDS_SECRET_ACCESS_KEY}}
